# Generated by Django 4.1.5 on 2023-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='actual_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='monthly_expenses',
            field=models.IntegerField(default=0),
        ),
    ]
